= Kubernetes Cluster on Google Cloud(GKE)
include::../pages/_attributes.adoc[]

[#pre-req]
== Pre-requisites

* https://console.cloud.google.com/[GCP Account^]
* https://cloud.google.com/sdk/docs/install[Google Cloud SDK^]

Navigate to Google Cloud setup folder `{cluster-gcp-repo}`:

[#civo-nav-folder]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{cluster-gcp-repo}
----

[NOTE]
====
Adjust link:{github-repo}/{cluster-gcp-repo}/terrraform.tfvars[terrraform.tfvars^] as per your cluster needs.
====

[#civo-terraform-variables]
== Terraform Variable

The cluster creation is configured using map `gloo_clusters` that supports the following keys:

[cols="^1s,^3,^1m", options="header"]
|===
| Variable | Description | Default

| region      
a| 
Google Cloud Region. The cluster will be created in one of the available zones in the region. You check the available regions using,
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
gcloud compute regions list
----
|

| vpc_name    
| The gloo mesh VPC name    
|     

| subnet_name    
| The goo mesh cluster subnet name name    
|

| machine_type
a| 
The Google Compute machine size to use, you can get the list of machine types using,
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
gcloud compute machine-types list 
----
|

| num_nodes   
| Number of nodes in GKE per cluster name          
| 3

| role
| The role of the cluster in gloo deployment management, workload etc.,
|

| kubernetes_version
a| 
The Kubernetes version to use with clusters,
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
gcloud container get-server-config --region=<region>
----
| 1.20

|===

An example `gloo_clusters` value:

[source,terraform]
----
gloo_clusters = {
  gloo-cluster-1 : { #<.>
    region             = "asia-south1" #<.>
    vpc_name           = "gloo-vpc" #<.>
    subnet_name        = "gloo-subnet"#<.>
    machine_type       = "n2-standard-4"#<.>
    num_nodes          = 2#<.>
    role               = "management"#<.>
    kubernetes_version = "1.20"#<.>
  }
}
----
<.> The cluster name, this will be the name of the kubernetes cluster
<.> The region where cluster will be created
<.> The VPC name to use for the cluster
<.> The Subnet name to use for the cluster
<.> The number of Kubernetes worker nodes for the cluster
<.> The role of the cluster, this matches to xref:setup.adoc#cloud-and-components[Cloud and Components]
<.> The Kubernetes version to use

[#gke-deploy-clusters]
== Deploy Clusters

[.console-input]
[source,bash,subs="attributes+,+macros"]
----
cp .env.example .env
----

Adjust the `.env` to suit your environment, e.g. 

[.console-output]
[source,bash,subs="attributes+,+macros"]
----
GOOGLE_APPLICATION_CREDENTIALS=foo-sa.json#<.>
GOOGLE_PROJECT=foo-project#<.>
TFVARS_FILE=local.tfvars#<.>
----
<.> The Google Cloud Service Account to use, if you dont have one check the https://cloud.google.com/iam/docs/creating-managing-service-account-keys[docs] to have one created. The service account should be able to create Kubernetes Clusters with the following roles: 
- Compute Network Admin
- Kubernetes Engine Admin
- Service Account User
<.> The Google Cloud Project to use
<.> The customized terraform variables (local dev file)

[.console-input]
[source,bash,subs="attributes+,+macros"]
----
make apply
----

The successful command shows an output like,

[source,terraform]
----
gloo_clusters_info = {
       gloo-cluster-1 = {
           kubernetes_cluster_endpoint = 192.168.1.1
           kubernetes_cluster_name     = "gloo-cluster-1"
           kubernetes_cluster_zone     = "asia-south1-a"
        }
       gloo-cluster-2 = {
           kubernetes_cluster_endpoint = 192.168.1.2
           kubernetes_cluster_name     = "gloo-cluster-2"
           kubernetes_cluster_zone     = "asia-south1-a"
        }
       gloo-cluster-3 = {
           kubernetes_cluster_endpoint = 192.168.1.3
           kubernetes_cluster_name     = "gloo-cluster-3"
           kubernetes_cluster_zone     = "asia-south1-a"
        }
    }
----

== Get Kubernetes Cluster Credentials

Use the `kubernetes_cluster_name` and `kubernetes_cluster_zone` from the `gloo_clusters_info` with `gcloud` to retrieve the kubernetes credentials,

[.console-input]
[source,bash,subs="attributes+,+macros"]
----
gcloud container clusters get-credentials pass:[$kubernetes_cluster_name] \
  --zone pass:[$kubernetes_cluster_zone]
----
