---
- name: "Cloud Two"
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices

  vars:
    cluster_name: cloud-2
    kind_create: true
    ####
    ## Gloo Edge Configuration
    ####
    # Deploy Gloo Edge
    deploy_gloo_edge: true
    gloo_write_namespace: my-gloo
    # gloo_discovery_enabled: false
    gloo_edge_edition: ee
    gloo_watch_namespaces:
      - hybrid-cloud
    gloo_proxy_nodeport: true

  roles:
    - kameshsampath.kubernetes_spices.kind
    - kameshsampath.kubernetes_spices.k8s_app_spices
