apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualGateway
metadata:
  name: frontend-gateway
spec:
  connectionHandlers:
    - http:
        routeConfig:
          - virtualHostSelector:
              namespaces:
                - "gloo-mesh"
  ingressGatewaySelectors:
    - portName: http2
      destinationSelectors:
        - kubeServiceMatcher:
            clusters:
              - cluster-1
              - cluster-2
            labels:
              istio: ingressgateway
            namespaces:
              - istio-system
