name: Dev Docs

on:
  push:
    branches:
      - main
env:
  SITE_DIR: "gh-pages"
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: site.yml
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.2.1
        with:
          # ACCESS_TOKEN: # optional
          GITHUB_TOKEN: "${{ github.token}}"
          FOLDER: "${{ env.SITE_DIR }}"
          BRANCH: "gh-pages"
          COMMIT_MESSAGE: "[CI] Publish Documentation for ${{ github.sha }}"
