namespace: hybrid-cloud
commonLabels:
  app.kubernetes.io/component: hybrid-cloud-frontend
  app: hybrid-cloud-frontend
  version: v1.0
secretGenerator:
  - name: pgsql-credentials
    literals:
      - username=demo
      - password=pa55Word!
      - database=demodb
      - hostname=postgresql.db.svc.cluster.local
      - port=5432
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml
